# 🧬 Script to check GFAP raw and normalized expression values

# --- Configuration ---
# Path to the dds.rds file generated by deseq2_analysis2.R (using DESeq2 v1.24.0)
dds_file_path <- "/home/layanomics/CrispAstro-Seq/04_differential_expression/results_DESeq2_1.24.0/dds.rds"

# Ensembl Gene ID for GFAP (from your plotting script)
Gfap_ensg_id <- "ENSG00000131095"

# --- Load required library ---
# Ensure DESeq2 is loaded to use its functions like counts() and colData()
library(DESeq2)
library(dplyr) # For data manipulation if needed, but primarily using base R here

# --- Load the dds object ---
if (!file.exists(dds_file_path)) {
  stop(paste(
    "Error: dds.rds file not found at", dds_file_path,
    ". Please ensure deseq2_analysis2.R ran successfully and saved the file there."
  ))
}
dds <- readRDS(dds_file_path)

cat("✅ Successfully loaded dds object from:", dds_file_path, "\n")
cat("DESeq2 version used to create this dds object (from your environment):", as.character(packageVersion("DESeq2")), "\n\n")

# --- Verify GFAP gene ID ---
if (!(Gfap_ensg_id %in% rownames(dds))) {
  stop(paste("Error: GFAP gene ID", Gfap_ensg_id, "not found in the dds object's row names."))
}
cat("✅ GFAP gene ID found in dds object.\n\n")

# --- Extract and Print Raw Counts for GFAP ---
raw_counts_gfap <- counts(dds, normalized = FALSE)[Gfap_ensg_id, ]
cat("--- Raw counts for GFAP (ENSG00000131095) across all samples ---\n")
print(raw_counts_gfap)
cat("\n")

# --- Extract and Print Normalized Counts for GFAP ---
norm_counts_gfap <- counts(dds, normalized = TRUE)[Gfap_ensg_id, ]
cat("--- Normalized counts for GFAP (ENSG00000131095) across all samples ---\n")
print(norm_counts_gfap)
cat("\n")

# --- Extract and Print Sample Conditions ---
sample_conditions <- as.character(colData(dds)$condition) # Convert to character for cleaner printing
names(sample_conditions) <- colnames(dds) # Add sample names for clarity
cat("--- Sample conditions ---\n")
print(sample_conditions)
cat("\n")

# --- Calculate and Print WT Mean Normalized Count ---
wt_norm_counts_gfap <- norm_counts_gfap[sample_conditions == "WT"]
wt_mean_norm_gfap <- mean(wt_norm_counts_gfap)
cat("--- Mean normalized counts for GFAP in WT condition ---\n")
print(wt_mean_norm_gfap)
cat("\n")

# --- Calculate and Print R270X Mean Normalized Count ---
r270x_norm_counts_gfap <- norm_counts_gfap[sample_conditions == "R270X"]
r270x_mean_norm_gfap <- mean(r270x_norm_counts_gfap)
cat("--- Mean normalized counts for GFAP in R270X condition ---\n")
print(r270x_mean_norm_gfap)
cat("\n")

# --- Calculate and Print Mean Relative Expression for R270X (normalized to WT) ---
r270x_relative_gfap <- r270x_mean_norm_gfap / wt_mean_norm_gfap
cat("--- Mean relative expression for GFAP in R270X (normalized to WT) ---\n")
print(r270x_relative_gfap)
cat("\n")

cat("🎉 GFAP value check complete.\n")
